module Kuby::KubeDB::DSL::Api::V1
  autoload :RestServerSpec, 'kuby/kube-db/dsl/api/v1/rest_server_spec'
  autoload :ServiceTemplateSpec, 'kuby/kube-db/dsl/api/v1/service_template_spec'
  autoload :SwiftSpec, 'kuby/kube-db/dsl/api/v1/swift_spec'
  autoload :S3Spec, 'kuby/kube-db/dsl/api/v1/s3_spec'
  autoload :PodTemplateSpec, 'kuby/kube-db/dsl/api/v1/pod_template_spec'
  autoload :ServiceMonitorSpec, 'kuby/kube-db/dsl/api/v1/service_monitor_spec'
  autoload :B2Spec, 'kuby/kube-db/dsl/api/v1/b2_spec'
  autoload :ObjectMeta, 'kuby/kube-db/dsl/api/v1/object_meta'
  autoload :PodSpec, 'kuby/kube-db/dsl/api/v1/pod_spec'
  autoload :PrometheusExporterSpec, 'kuby/kube-db/dsl/api/v1/prometheus_exporter_spec'
  autoload :AzureSpec, 'kuby/kube-db/dsl/api/v1/azure_spec'
  autoload :LocalSpec, 'kuby/kube-db/dsl/api/v1/local_spec'
  autoload :ServicePort, 'kuby/kube-db/dsl/api/v1/service_port'
  autoload :Backend, 'kuby/kube-db/dsl/api/v1/backend'
  autoload :ServiceSpec, 'kuby/kube-db/dsl/api/v1/service_spec'
  autoload :AgentSpec, 'kuby/kube-db/dsl/api/v1/agent_spec'
  autoload :PrometheusSpec, 'kuby/kube-db/dsl/api/v1/prometheus_spec'
  autoload :GCSSpec, 'kuby/kube-db/dsl/api/v1/gcs_spec'
end
