module Kuby::KubeDB::DSL::Authorization::V1alpha1
  autoload :DatabaseAccessRequestSpec, 'kuby/kube-db/dsl/authorization/v1alpha1/database_access_request_spec'
  autoload :PostgresRoleCondition, 'kuby/kube-db/dsl/authorization/v1alpha1/postgres_role_condition'
  autoload :DatabaseAccessRequestList, 'kuby/kube-db/dsl/authorization/v1alpha1/database_access_request_list'
  autoload :RoleReference, 'kuby/kube-db/dsl/authorization/v1alpha1/role_reference'
  autoload :Lease, 'kuby/kube-db/dsl/authorization/v1alpha1/lease'
  autoload :MongoDBRoleSpec, 'kuby/kube-db/dsl/authorization/v1alpha1/mongo_db_role_spec'
  autoload :DatabaseAccessRequestStatus, 'kuby/kube-db/dsl/authorization/v1alpha1/database_access_request_status'
  autoload :MySQLRoleSpec, 'kuby/kube-db/dsl/authorization/v1alpha1/my_sql_role_spec'
  autoload :PostgresRoleSpec, 'kuby/kube-db/dsl/authorization/v1alpha1/postgres_role_spec'
  autoload :MongoDBRoleCondition, 'kuby/kube-db/dsl/authorization/v1alpha1/mongo_db_role_condition'
  autoload :PostgresRoleList, 'kuby/kube-db/dsl/authorization/v1alpha1/postgres_role_list'
  autoload :MongoDBRoleList, 'kuby/kube-db/dsl/authorization/v1alpha1/mongo_db_role_list'
  autoload :MySQLRoleStatus, 'kuby/kube-db/dsl/authorization/v1alpha1/my_sql_role_status'
  autoload :DatabaseAccessRequestCondition, 'kuby/kube-db/dsl/authorization/v1alpha1/database_access_request_condition'
  autoload :MySQLRoleCondition, 'kuby/kube-db/dsl/authorization/v1alpha1/my_sql_role_condition'
  autoload :MySQLRole, 'kuby/kube-db/dsl/authorization/v1alpha1/my_sql_role'
  autoload :DatabaseAccessRequest, 'kuby/kube-db/dsl/authorization/v1alpha1/database_access_request'
  autoload :MySQLRoleList, 'kuby/kube-db/dsl/authorization/v1alpha1/my_sql_role_list'
  autoload :MongoDBRoleStatus, 'kuby/kube-db/dsl/authorization/v1alpha1/mongo_db_role_status'
  autoload :PostgresRoleStatus, 'kuby/kube-db/dsl/authorization/v1alpha1/postgres_role_status'
  autoload :MongoDBRole, 'kuby/kube-db/dsl/authorization/v1alpha1/mongo_db_role'
  autoload :PostgresRole, 'kuby/kube-db/dsl/authorization/v1alpha1/postgres_role'
end
